version: "3.1"

services:
  app:
    container_name: TESTGOENGINE
    build: ./engine
    environment:
      Port: 3010
    ports:
      - 3010:3010
    depends_on:
      - db

  db:
    container_name: TESTGODB
    image: postgres
    environment:
      - POSTGRES_PASSWORD=dncvgua5r3
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    ports:
      - 5432:5432
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data     
    
